### PR TITLE
Fixed the pre ingest hook.

### PR DESCRIPTION
**Pull request by nigelgbanks**

### CODE REVIEW

**Comment by jonathangreen** [comment]
Does this work? Did we test it? We don't set it back to active after this do we?

**Comment by nigelgbanks** [comment]
The hook gets called now, it wasn't before. I'm not sure if it works in practice, as on caltech.dgi fedora is sending an unauthorized error when attempting to ingest objects as any user aside from user 1.

**Comment by jonathangreen** [comment]
This hook got removed in the work you did on ingest. The reason mitch made the alter was to alter after the pre ingest to get around the formbuilder modifying state. I just wanted to make sure in the new system this still works.

**Comment by nigelgbanks** [comment]
It would still work, this hook is called before the ingest is attempted not at the start of the multipage ingest process. So the only call that follows this hook is repository->ingestObject

**Pull request merged**
